### ISSUE TITLE
Stabilize and polish Outbound translation UI

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#54]
- [x] Why takes a long time to load and inject the form widget into the page.
- [x] The form widget should always have the topmost z-index.  Some STRs here: https://github.com/mozilla/firefox-translations/issues/16
- [x] Polished UI with some usage instructions 
- [x] Translations are broken in the latest messaging batched mechanism
- [x] Add dynamic scrolling to the backtranslation textarea
- [x] Display the widget when input texts are selected besides only textareas
- [x] Listen to mutations that add new editable forms to the Dom after the first scan (https://github.com/mozilla/firefox-translations/issues/12). Basically unhook to the mutation listener on inpage and have its own for OT looking for what's pertinent.
- [x] Outbound Translation messages to the translation worker should have top priority.
- [x] Error when widget loses focus: https://github.com/mozilla/firefox-translations/issues/57
- [x] Rebase
