### ISSUE TITLE
[META] Addon signing

### ISSUE THREAD

**Issue by andrenatal** [mozilla/firefox-translations#74]
Actionable items:
 - [x] Remove the legacy in-tree version from Nightly but make sure we keep the pref so the addon could turn on the preferences panel: https://github.com/mozilla/gecko-dev/blob/master/browser/components/preferences/main.js#L538)
 - [x] Bump the version before freezing
 - [x] Follow these procedures to prepare the addon for signing: https://github.com/mozilla-extensions/xpi-manifest/tree/master/docs
 - [x] ask in [#addons-pipeline](https://mozilla.slack.com/archives/CMKP7NPKN) for a new release off revision xxxxx for firefox-translations when we have a final release version
 - [x] Perform addon/security review from the addons team in order to have it signed
 - [x] Provide architecture docs: https://github.com/mozilla/firefox-translations/issues/39
 - [x] Provide a more detailed explanation and references to the generic data review policy, and follow the data review addons policy as well: https://extensionworkshop.com/documentation/publish/add-on-policies/

**Comment by andrenatal** [comment]
Which are these https://github.com/mozilla-extensions/xpi-manifest/tree/master/docs
